name: Strava CTA Checker

on:
  schedule:
    # Run every 5 minutes between 7am and 10pm UTC
    - cron: '*/5 7-22 * * *'
  workflow_dispatch:
    # Allow manual triggering

env:
  UV_VERSION: "0.6.14"

jobs:
  check-strava-activities:
    runs-on: ubuntu-latest
    permissions:
      # Required for GitHub CLI to update secrets
      contents: read
      actions: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Setup dependencies
        run: uv sync --frozen
      - name: Check for Strava activities
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_TOKEN_EXPIRES_AT: ${{ secrets.STRAVA_TOKEN_EXPIRES_AT }}
        run: |
          uv run python -m strava_cta.check_activities